[package]
name = "breed-trade-station"
version = "0.1.0"
edition = "2021"
rust-version = "1.88"
publish = false

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", default-features = false, features = ["wry", "compression", "dynamic-acl", "x11"] }

[features]
custom-protocol = ["tauri/custom-protocol"]
