name: Docker Build

on:
  pull_request:
    branches: [main]
    paths:
      - compose.yaml
      - apps/game/Dockerfile
      - apps/server/Dockerfile
      - .github/workflows/docker-build.yml
  push:
    branches: [main]

jobs:
  build-game-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build game Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: apps/game/Dockerfile
          push: false
          tags: bts/game:ci
          cache-from: type=gha
          cache-to: type=gha,mode=max
